5 responsive tweaks
Kenzie-Tech-Solutions/theRoyalCanine pull request #6
Opened 2024-01-08 02:57 UTC by Iconians

added and updated everything in the issues plus the additional info provided via discord. I tried a React response carousel library but felt it wasn't exactly what the client would want so coded one from scratch seems to work like the provided example

2024-01-08 15:15 UTC, mikesz88 requested changes
Is this already in GitHub pages? 
How fast is the according for the images? Seems fast, but I will let the client decide. 

Make those changes and let me know when it is ready again and on GitHub pages. From there I will send it the GitHub pages to the client and get her recommended changes.

2024-01-08 15:15 UTC, mikesz88 commented on src/pages/Events/Events.tsx
@Iconians Where are the event examples we had here?

2024-01-08 15:15 UTC, mikesz88 commented on src/pages/Home/Home.tsx
> +      <section className={style.imageSection}>
Let's continue the background of what was above with the dogs.
![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/9a539506-e399-4185-ab08-57ad0c6560d7)

Lets slide those images to the middle and make them space evenly. 
In regards to that picture of the client, we might just need to crop the image ourselves and test it out so it does not look as distorted like we see it. Make the images smaller. Let's go with something like 450 L and W and obviously responsive.

2024-01-08 15:15 UTC, mikesz88 commented on src/pages/Home/Home.tsx
>                <h1>The Royal Canine</h1>
The name is missing part of it? 
![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/1f57c297-aaf9-4dd4-8ffe-97f024da1add)
![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/181bed40-015a-403a-87b4-5f644f70c6ed)

2024-01-08 15:15 UTC, mikesz88 commented on src/Components/Footer/Footer.tsx
> +        <div className={styles.brandName}>
Let's center this all the way. 
![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/8666e757-6f92-4d45-96b8-8f5a908651cc)

2024-01-08 15:15 UTC, mikesz88 commented on src/utils/faqArray.ts
> +    question: "Payment at the Machine:",
Take out the semi-colons of all the questions
![image](https://github.com/Kenzie-Tech-Solutions/theRoyalCanine/assets/88916004/80bca7cb-f937-49b9-8390-5ba3832be0dd)

2024-01-08 15:59 UTC, Iconians commented on src/pages/Events/Events.tsx
under this task I thought you were to get rid of the examples, I'll put them back 
Events
Navbar only

2024-01-08 23:41 UTC, Iconians commented
believe I fixed all those change orders

2024-01-09 13:39 UTC, mikesz88 approved these changes
lgtm

2024-01-09 13:39 UTC, merged